
plugins { 
id 'com.android.application' 
}

 android { 
 compileSdkVersion 30 
 buildToolsVersion "30.0.3"
 

 defaultConfig { 
     applicationId "com.shubham.admob"                
     minSdkVersion 21
     targetSdkVersion 30
     versionCode 1
     versionName "1.0" 
     
     testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner" 
     } 
     buildTypes { 
     release { 
        minifyEnabled false proguardFiles    getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' 
 }
 } 
 compileOptions { 
 sourceCompatibility JavaVersion.VERSION_1_8 targetCompatibility JavaVersion.VERSION_1_8 
 }
  buildFeatures { 
  viewBinding true }
  } 
  
  } 
  dependencies {
  
  implementation 'com.google.android.gms:play-services-ads:20.5.0'
  implementation 'androidx.appcompat:appcompat:1.3.0'          implementation 'com.google.android.material:material:1.3.0' testImplementation 'junit:junit:4.+' androidTestImplementation 'androidx.test.ext:junit:1.1.2' androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0' 
   // Admob
    implementation 'com.google.android.gms:play-services-ads:20.2.0' }
    <?xml version="1.0" encoding="utf-8"?>
     <manifestxmlns:android="http://schemas.android.com/apk/res/android" package="com.shubham.ads"> 
     				
<uses-permission android:name="android.permission.INTERNET" /> 
<application
    android:allowBackup="true"      android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:roundIcon="@mipmap/ic_launcher_round" android:supportsRtl="true"
android:theme="@style/Theme.Ads"> 

<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" 
android:value="ca-app-pub-7038812199895418~2033480865"/>

<activity android:name=".MainActivity"> <intent-filter> <action android:name="android.intent.action.MAIN" /> 
				
				<activity android:name=".MainActivity"> <intent-filter> 
					<action android:name="android.intent.action.MAIN" /> 
												<category android:name="android.intent.category.LAUNCHER" /> </intent-filter> </activity> </application> </manifest>
												
							
								<?xml version="1.0" encoding="utf-8"?> <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto" xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent" android:layout_height="match_parent" tools:context=".MainActivity"> <com.google.android.gms.ads.AdView android:id="@+id/adView" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_alignParentBottom="true" android:layout_centerHorizontal="true" app:adSize="BANNER" app:adUnitId="ca-app-pub-7038812199895418/6198266200" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintHorizontal_bias="0.5" app:layout_constraintStart_toStartOf="parent" /> </androidx.constraintlayout.widget.ConstraintLayout>			
												
												
												
				import.androidx.appcompat.appcompatActivity	
				import .android.os.Bundle
         import com.google.android.gms.ads.MobileAds;
         
class MainActivity : AppCompatActivity() { lateinit var mAdView : 
AdView override fun onCreate(savedInstanceState: Bundle?) { 
super.onCreate(savedInstanceState) setContentView(R.layout.activity_main) MobileAds.initialize(this) {}


		
